# Generated by Django 3.2.16 on 2022-11-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Field', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Name_cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Scientific_leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Second_name', models.TextField()),
                ('First_name', models.TextField()),
                ('Middle_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Second_name', models.TextField()),
                ('First_name', models.TextField()),
                ('Middle_name', models.TextField()),
            ],
        ),
    ]
